# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dist_processing_pb2 as dist__processing__pb2


class ImageTransferStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestImage = channel.unary_unary(
                '/dist_processing.ImageTransfer/RequestImage',
                request_serializer=dist__processing__pb2.ImageRequest.SerializeToString,
                response_deserializer=dist__processing__pb2.ImageReply.FromString,
                )
        self.ReturnImage = channel.unary_unary(
                '/dist_processing.ImageTransfer/ReturnImage',
                request_serializer=dist__processing__pb2.ProcessedImage.SerializeToString,
                response_deserializer=dist__processing__pb2.ImageDone.FromString,
                )


class ImageTransferServicer(object):
    """The greeting service definition.
    """

    def RequestImage(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestImage,
                    request_deserializer=dist__processing__pb2.ImageRequest.FromString,
                    response_serializer=dist__processing__pb2.ImageReply.SerializeToString,
            ),
            'ReturnImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnImage,
                    request_deserializer=dist__processing__pb2.ProcessedImage.FromString,
                    response_serializer=dist__processing__pb2.ImageDone.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dist_processing.ImageTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageTransfer(object):
    """The greeting service definition.
    """

    @staticmethod
    def RequestImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dist_processing.ImageTransfer/RequestImage',
            dist__processing__pb2.ImageRequest.SerializeToString,
            dist__processing__pb2.ImageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReturnImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dist_processing.ImageTransfer/ReturnImage',
            dist__processing__pb2.ProcessedImage.SerializeToString,
            dist__processing__pb2.ImageDone.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
